export const VENDOR_LOGIN_REQUEST = 'VENDOR_LOGIN_REQUEST'
export const VENDOR_LOGIN_SUCCESS = 'VENDOR_LOGIN_SUCCESS'
export const VENDOR_LOGIN_FAIL = 'VENDOR_LOGIN_FAIL'
export const VENDOR_LOGOUT = 'VENDOR_LOGOUT'

export const VENDOR_REGISTER_REQUEST = 'VENDOR_REGISTER_REQUEST'
export const VENDOR_REGISTER_SUCCESS = 'VENDOR_REGISTER_SUCCESS'
export const VENDOR_REGISTER_FAIL = 'VENDOR_REGISTER_FAIL'

export const VENDOR_DETAILS_REQUEST = 'VENDOR_DETAILS_REQUEST'
export const VENDOR_DETAILS_SUCCESS = 'VENDOR_DETAILS_SUCCESS'
export const VENDOR_DETAILS_FAIL = 'VENDOR_DETAILS_FAIL'
export const VENDOR_DETAILS_RESET = 'VENDOR_DETAILS_RESET'

export const VENDOR_LIST_REQUEST = 'VENDOR_LIST_REQUEST'
export const VENDOR_LIST_SUCCESS = 'VENDOR_LIST_SUCCESS'
export const VENDOR_LIST_FAIL = 'VENDOR_LIST_FAIL'
export const VENDOR_LIST_RESET = 'VENDOR_LIST_RESET'

export const VENDOR_DELETE_REQUEST = 'VENDOR_DELETE_REQUEST'
export const VENDOR_DELETE_SUCCESS = 'VENDOR_DELETE_SUCCESS'
export const VENDOR_DELETE_FAIL = 'VENDOR_DELETE_FAIL'

export const VENDOR_UPDATE_PROFILE_REQUEST = 'VENDOR_UPDATE_PROFILE_REQUEST'
export const VENDOR_UPDATE_PROFILE_SUCCESS = 'VENDOR_UPDATE_PROFILE_SUCCESS'
export const VENDOR_UPDATE_PROFILE_FAIL = 'VENDOR_UPDATE_PROFILE_FAIL'
export const VENDOR_UPDATE_PROFILE_RESET = 'VENDOR_UPDATE_PROFILE_RESET'

export const VENDOR_UPDATE_REQUEST = 'VENDOR_UPDATE_REQUEST'
export const VENDOR_UPDATE_SUCCESS = 'VENDOR_UPDATE_SUCCESS'
export const VENDOR_UPDATE_FAIL = 'VENDOR_UPDATE_FAIL'
export const VENDOR_UPDATE_RESET = 'VENDOR_UPDATE_RESET'