export const VENDORCREATION_LIST_REQUEST = 'VENDORCREATION_LIST_REQUEST'
export const VENDORCREATION_LIST_SUCCESS = 'VENDORCREATION_LIST_SUCCESS'
export const VENDORCREATION_LIST_FAIL = 'VENDORCREATION_LIST_FAIL'

export const VENDORCREATION_DETAILS_REQUEST = 'VENDORCREATION_DETAILS_REQUEST'
export const VENDORCREATION_DETAILS_SUCCESS = 'VENDORCREATION_DETAILS_SUCCESS'
export const VENDORCREATION_DETAILS_FAIL = 'VENDORCREATION_DETAILS_FAIL'

export const VENDORCREATION_DELETE_REQUEST = 'VENDORCREATION_DELETE_REQUEST'
export const VENDORCREATION_DELETE_SUCCESS = 'VENDORCREATION_DELETE_SUCCESS'
export const VENDORCREATION_DELETE_FAIL = 'VENDORCREATION_DELETE_FAIL'

export const VENDORCREATION_CREATE_REQUEST = 'VENDORCREATION_CREATE_REQUEST'
export const VENDORCREATION_CREATE_SUCCESS = 'VENDORCREATION_CREATE_SUCCESS'
export const VENDORCREATION_CREATE_FAIL = 'VENDORCREATION_CREATE_FAIL'
export const VENDORCREATION_CREATE_RESET = 'VENDORCREATION_CREATE_RESET'

export const VENDORCREATION_UPDATE_REQUEST = 'VENDORCREATION_UPDATE_REQUEST'
export const VENDORCREATION_UPDATE_SUCCESS = 'VENDORCREATION_UPDATE_SUCCESS'
export const VENDORCREATION_UPDATE_FAIL = 'VENDORCREATION_UPDATE_FAIL'
export const VENDORCREATION_UPDATE_RESET = 'VENDORCREATION_UPDATE_RESET'

export const VENDORCREATION_CREATE_REVIEW_REQUEST = 'VENDORCREATION_CREATE_REVIEW_REQUEST'
export const VENDORCREATION_CREATE_REVIEW_SUCCESS = 'VENDORCREATION_CREATE_REVIEW_SUCCESS'
export const VENDORCREATION_CREATE_REVIEW_FAIL = 'VENDORCREATION_CREATE_REVIEW_FAIL'
export const VENDORCREATION_CREATE_REVIEW_RESET = 'VENDORCREATION_CREATE_REVIEW_RESET'

export const VENDORCREATION_TOP_REQUEST = 'VENDORCREATION_TOP_REQUEST'
export const VENDORCREATION_TOP_SUCCESS = 'VENDORCREATION_TOP_SUCCESS'
export const VENDORCREATION_TOP_FAIL = 'VENDORCREATION_TOP_FAIL'
export const VENDORCREATION_TOP_RESET = 'VENDORCREATION_TOP_RESET'

export const VENDORCREATION_LIST_MY_REQUEST = 'VENDORCREATION_LIST_MY_REQUEST'
export const VENDORCREATION_LIST_MY_SUCCESS = 'VENDORCREATION_LIST_MY_SUCCESS'
export const VENDORCREATION_LIST_MY_FAIL = 'VENDORCREATION_LIST_MY_FAIL'
export const VENDORCREATION_LIST_MY_RESET = 'VENDORCREATION_LIST_MY_RESET'